Merge dev to main
MillenniumMachines/millenniummachines.github.io pull request #19
Opened 2024-02-22 10:09 UTC by EdwardChamberlain

Restructures to add space for new products
Adds Long John MD guide

fixes #17 
fixes #8

2024-02-22 16:01 UTC, benagricola commented
Merged `main` into `dev` to fix the conflicting images.

2024-02-22 16:03 UTC, benagricola commented on docs/index.md
> +Docs comming Soon! For now please use the PDF manual.
*Puts on spellcheck hat*: "Docs coming soon!"

2024-02-22 16:03 UTC, benagricola commented on docs/index.md
> +Docs comming Soon! For now please use the PDF manual.
Same here

2024-02-22 16:07 UTC, EdwardChamberlain commented on docs/index.md
> +Docs comming Soon! For now please use the PDF manual.
oops - resolved in 9d0e27d

2024-02-22 16:52 UTC, benagricola requested changes
Can we change the Loctite name to "medium-strength thread-lock" as noted? I doubt many, if any people building a mill will fall foul of picking the "wrong" Loctite but sods law is we would somehow find that one person :sweat_smile: 

Other than that, looks great to me, nice work :+1:

2024-02-22 16:52 UTC, benagricola commented on docs/long-john/assembly_manual/assembly_manual.md
> +!!! info annotate "Loctite"
I switched away from using the term "Loctite" in the assembly manual as it's a brand name (which also sells Superglue!) rather than the product.

The term I went with was "medium-strength thread-lock" and in one place "generally, blue" is mentioned, see [here](https://millenniummachines.github.io/docs/assembly_manual/chapters/y_axis_assembly/#xy-plate-orientation)

I think we should go with "medium-strength thread-lock" when talking about this, but using Loctite 243 or Loctite 248 (I prefer, slightly lower breaking torque and comes in a stick!) as an example would be fine :+1:

2024-02-22 20:22 UTC, EdwardChamberlain commented on docs/long-john/assembly_manual/assembly_manual.md
> +!!! info annotate "Loctite"
moved to 'threadlocker' consistently

2024-02-23 07:30 UTC, benagricola commented on docs/milo/faq.md
>  Do not use permanent or semi-permanent thread-lock, or red colour thread-lock unless it is specifically marked as medium strength.
```suggestion
Do not use permanent or semi-permanent threadlockers, or red colour threadlockers unless it is specifically marked as medium strength.
```

2024-02-23 09:05 UTC, benagricola commented
Last commit just changes `thread-lock` to `threadlock` across the docs so everything should consistently refer to `threadlock`, `threadlocker`, `threadlockers`, or `threadlocking` now

2024-02-23 09:05 UTC, benagricola approved these changes

2024-02-23 09:06 UTC, merged